apiVersion: apps/v1
kind: Deployment
metadata:    
  name: nginx-deploy  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod  
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: nginx-app
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
          - containerPort: 80
      # imagePullSecrets:
      # - name: <secret_name>
      nodeSelector:        
        agentpool: iotnodepool
